import { LifeStage } from '../types';

export const LIFE_STAGES: LifeStage[] = [
  {
    id: 'just_arrived',
    name: 'Just Arrived',
    subtitle: 'First 90 Days',
    emoji: '✈️',
    icon: 'airplane-landing',
    color: '#1565C0',
    timeline: '0–3 months in the US',
    description: 'The critical first steps every immigrant must take to get financially grounded in the US.',
    topics: [
      { id: 'ja_1', title: 'How to open a US bank account without a Social Security Number', description: 'ITIN, passport-based accounts, credit unions that accept immigrants', priority: 'high', communities: ['general'], visaTypes: ['F1', 'H1B', 'Undocumented', 'Tourist'] },
      { id: 'ja_2', title: 'ITIN vs SSN — what\'s the difference and which do you need?', description: 'When each applies, how to apply, timelines', priority: 'high', communities: ['general'] },
      { id: 'ja_3', title: 'First 5 financial moves after landing in the US', description: 'Bank account, phone plan, housing, ID, budget setup', priority: 'high', communities: ['general'] },
      { id: 'ja_4', title: 'What documents you need for US financial life', description: 'Passport, visa, ITIN, ITIN letter, proof of address', priority: 'medium', communities: ['general'] },
      { id: 'ja_5', title: 'Understanding US money — coins, bills, checks, Zelle, Venmo', description: 'Payment systems that confuse new arrivals', priority: 'medium', communities: ['african', 'south_asian', 'east_asian'] },
      { id: 'ja_6', title: 'How to send money home in your first month (cheapest options)', description: 'Remitly, Wise, Zelle to specific countries', priority: 'high', communities: ['hispanic_latino', 'african', 'south_asian', 'caribbean'] },
    ],
  },
  {
    id: 'first_job',
    name: 'First Job in the US',
    subtitle: 'Employment & Income',
    emoji: '💼',
    icon: 'briefcase',
    color: '#2E7D32',
    timeline: 'When you get your first US paycheck',
    description: 'Decoding the US employment system — paychecks, benefits, taxes, and rights.',
    topics: [
      { id: 'fj_1', title: 'How to read your first US paycheck (what all those deductions mean)', description: 'FICA, federal/state tax, Social Security, Medicare explained', priority: 'high', communities: ['general'] },
      { id: 'fj_2', title: 'What is a W-4 and how should immigrants fill it out?', description: 'Withholding, allowances, 2024 redesign', priority: 'high', communities: ['general'] },
      { id: 'fj_3', title: '401(k) explained — should you enroll in your first job?', description: 'Employer match, vesting, contribution limits', priority: 'high', communities: ['general'] },
      { id: 'fj_4', title: 'Health insurance at work — HMO vs PPO, deductibles, what to pick', description: 'Open enrollment, coverage tiers, dependent coverage', priority: 'high', communities: ['general'] },
      { id: 'fj_5', title: 'Social Security contributions for immigrants — will you ever get it back?', description: 'SSA rules for non-citizens, totalization agreements', priority: 'medium', communities: ['general'] },
      { id: 'fj_6', title: 'Gig economy income as an immigrant — Uber, DoorDash, freelance taxes', description: '1099-NEC, self-employment tax, quarterly payments', priority: 'high', communities: ['hispanic_latino', 'african', 'caribbean'] },
      { id: 'fj_7', title: 'Your employee rights as an immigrant worker', description: 'Wage theft, discrimination protections, whistleblower rights', priority: 'medium', communities: ['hispanic_latino', 'south_asian', 'african'] },
    ],
  },
  {
    id: 'credit_zero',
    name: 'Building Credit from Zero',
    subtitle: 'Credit Foundation',
    emoji: '📈',
    icon: 'chart-line',
    color: '#6A1B9A',
    timeline: 'Month 1 onwards',
    description: 'Your home country credit history means nothing here. Build a US credit score from scratch.',
    topics: [
      { id: 'cz_1', title: 'Why your credit score from home doesn\'t transfer to the US', description: 'How US credit bureaus work, why you start at zero', priority: 'high', communities: ['general'] },
      { id: 'cz_2', title: 'Best secured credit cards for immigrants in 2025', description: 'Deposits, APRs, cards that don\'t require SSN', priority: 'high', communities: ['general'] },
      { id: 'cz_3', title: 'The 5 credit score factors explained for first-gen credit builders', description: 'Payment history, utilization, age, mix, inquiries', priority: 'high', communities: ['general'] },
      { id: 'cz_4', title: 'Credit Karma vs myFICO — how to check your score for free', description: 'Soft vs hard inquiries, VantageScore vs FICO', priority: 'medium', communities: ['general'] },
      { id: 'cz_5', title: 'From 0 to 700 credit score in 12 months — realistic roadmap', description: 'Month-by-month action plan', priority: 'high', communities: ['general'] },
      { id: 'cz_6', title: 'Becoming an authorized user on someone\'s card — how it works', description: 'Piggybacking credit, risks, family dynamics', priority: 'medium', communities: ['hispanic_latino', 'south_asian', 'east_asian'] },
      { id: 'cz_7', title: 'Credit builder loans — what they are and which banks offer them', description: 'Self Inc, credit unions, community banks', priority: 'medium', communities: ['african', 'caribbean', 'hispanic_latino'] },
    ],
  },
  {
    id: 'visa_status',
    name: 'Visa & Immigration Status',
    subtitle: 'Status-Specific Finance',
    emoji: '🛂',
    icon: 'passport',
    color: '#E65100',
    timeline: 'Ongoing — changes with every status update',
    description: 'Your immigration status directly shapes what financial tools you can and cannot access.',
    topics: [
      { id: 'vs_1', title: 'H-1B holder financial guide — investing, 401k, buying a home', description: 'Status uncertainty, portability, tax treaty benefits', priority: 'high', communities: ['south_asian', 'east_asian'], visaTypes: ['H1B'] },
      { id: 'vs_2', title: 'F-1 student financial guide — working, OPT income, taxes', description: 'CPT, OPT, STEM OPT, 1042-S forms', priority: 'high', communities: ['south_asian', 'east_asian', 'middle_eastern'], visaTypes: ['F1'] },
      { id: 'vs_3', title: 'Green Card holder vs US citizen — 5 key financial differences', description: 'Tax obligations, benefits, investment options', priority: 'high', communities: ['general'], visaTypes: ['Green Card'] },
      { id: 'vs_4', title: 'Financial guide for undocumented immigrants', description: 'ITIN account options, tax filing, avoid predatory services', priority: 'high', communities: ['hispanic_latino', 'caribbean', 'african'], visaTypes: ['Undocumented'] },
      { id: 'vs_5', title: 'DACA recipient financial guide — what you can and can\'t access', description: 'Work authorization, credit, home buying with DACA', priority: 'high', communities: ['hispanic_latino'], visaTypes: ['DACA'] },
      { id: 'vs_6', title: 'TN visa (Canada/Mexico) financial guide', description: 'Cross-border tax, banking, retirement', priority: 'medium', communities: ['hispanic_latino'], visaTypes: ['TN'] },
      { id: 'vs_7', title: 'What happens to your finances when your visa expires or changes', description: 'Status change, grace periods, financial continuity', priority: 'high', communities: ['general'] },
      { id: 'vs_8', title: 'Tax treaties — does your home country have one with the US?', description: 'List of treaties, how to claim them, Form 8833', priority: 'medium', communities: ['south_asian', 'east_asian', 'eastern_european'] },
    ],
  },
  {
    id: 'emergency_fund',
    name: 'Emergency Fund',
    subtitle: 'Financial Safety Net',
    emoji: '🛡️',
    icon: 'umbrella',
    color: '#0277BD',
    timeline: 'Build before investing anything else',
    description: 'The foundation that protects immigrant families from catastrophic financial setbacks.',
    topics: [
      { id: 'ef_1', title: 'Why immigrants need a bigger emergency fund than the standard advice', description: 'Visa status risk, family obligations, deportation risk', priority: 'high', communities: ['general'] },
      { id: 'ef_2', title: 'The $1,000 starter emergency fund — how to get there fast', description: 'Side hustles, cutting costs, timeline', priority: 'high', communities: ['general'] },
      { id: 'ef_3', title: 'High-yield savings accounts for immigrants (no SSN options)', description: 'Marcus, Ally, online banks, rates comparison', priority: 'high', communities: ['general'] },
      { id: 'ef_4', title: 'Building an emergency fund while sending remittances home', description: 'The 50/30/20 remix for immigrants who support family abroad', priority: 'high', communities: ['hispanic_latino', 'african', 'south_asian', 'caribbean'] },
      { id: 'ef_5', title: 'What counts as a real emergency vs a want?', description: 'Teaching financial discipline, emergency fund rules', priority: 'medium', communities: ['general'] },
      { id: 'ef_6', title: 'Emergency fund in the US vs home country — should you split it?', description: 'Currency risk, accessibility, family emergency abroad', priority: 'medium', communities: ['general'] },
    ],
  },
  {
    id: 'moving_housing',
    name: 'Moving & Housing',
    subtitle: 'Renting & Settling',
    emoji: '🏠',
    icon: 'home-city',
    color: '#4E342E',
    timeline: 'First 6 months, and whenever you move',
    description: 'Navigating the US rental market as an immigrant — leases, deposits, landlord red flags.',
    topics: [
      { id: 'mh_1', title: 'How to rent an apartment with no US credit history', description: 'Co-signers, larger deposit, letter of employment', priority: 'high', communities: ['general'] },
      { id: 'mh_2', title: 'Understanding a US lease agreement (clause by clause)', description: 'Security deposit, subletting, notice requirements', priority: 'high', communities: ['general'] },
      { id: 'mh_3', title: 'What landlords can and cannot ask immigrant tenants (fair housing law)', description: 'Fair Housing Act, discrimination, visa status questions', priority: 'high', communities: ['general'] },
      { id: 'mh_4', title: 'Setting up utilities as a new immigrant — gas, electric, internet', description: 'Deposits, account setup without credit, bundling', priority: 'medium', communities: ['general'] },
      { id: 'mh_5', title: 'Renter\'s insurance for immigrants — why it matters and how to get it', description: 'Coverage, cost, how to file a claim', priority: 'medium', communities: ['general'] },
      { id: 'mh_6', title: 'Moving to a new state — financial checklist for immigrants', description: 'State taxes, DMV, bank account changes, new lease', priority: 'medium', communities: ['general'] },
      { id: 'mh_7', title: 'City vs suburbs cost comparison for immigrant families', description: 'Housing cost, commute, school districts, community', priority: 'low', communities: ['hispanic_latino', 'south_asian', 'african'] },
    ],
  },
  {
    id: 'remittances_family',
    name: 'Remittances & Family',
    subtitle: 'Supporting Loved Ones Abroad',
    emoji: '💸',
    icon: 'send',
    color: '#00695C',
    timeline: 'Ongoing for most immigrants',
    description: 'Sending money home efficiently while still building wealth in the US.',
    topics: [
      { id: 'rf_1', title: 'Cheapest ways to send money to Mexico, Guatemala, El Salvador', description: 'Remitly, Wise, Western Union comparison, exchange rates', priority: 'high', communities: ['hispanic_latino'] },
      { id: 'rf_2', title: 'Best remittance apps for sending money to India, Pakistan, Bangladesh', description: 'Wise, Remitly, PayPal, bank wire comparison', priority: 'high', communities: ['south_asian'] },
      { id: 'rf_3', title: 'Sending money to Nigeria, Ghana, Kenya, Ethiopia — lowest fees', description: 'WorldRemit, Remitly, Chipper Cash, bank comparisons', priority: 'high', communities: ['african'] },
      { id: 'rf_4', title: 'The real cost of sending $500 home — total fee breakdown', description: 'Transfer fee + exchange rate margin = true cost', priority: 'high', communities: ['general'] },
      { id: 'rf_5', title: 'How remittances affect your US taxes', description: 'Gift tax rules, $17k annual exclusion, IRS form 3520', priority: 'high', communities: ['general'] },
      { id: 'rf_6', title: 'How much of your income should go to remittances? (The honest conversation)', description: 'Setting boundaries, talking to family, balancing US savings', priority: 'high', communities: ['general'] },
      { id: 'rf_7', title: 'Risks of informal money transfer (hawala, sending cash)', description: 'Legal risks, fraud, safer alternatives', priority: 'high', communities: ['middle_eastern', 'south_asian', 'african'] },
      { id: 'rf_8', title: 'Helping parents abroad with US financial tools', description: 'Joint accounts, wire transfers, power of attorney', priority: 'medium', communities: ['general'] },
    ],
  },
  {
    id: 'liquidity',
    name: 'Liquidity & Cash Flow',
    subtitle: 'Managing Your Money Flow',
    emoji: '💧',
    icon: 'water',
    color: '#0288D1',
    timeline: 'Ongoing financial management',
    description: 'Understanding liquid vs illiquid assets and managing cash flow with an immigrant income.',
    topics: [
      { id: 'lq_1', title: 'What does "liquid" mean and why it matters for immigrants', description: 'Liquid vs illiquid, why immigrants need more liquidity', priority: 'high', communities: ['general'] },
      { id: 'lq_2', title: 'How much cash should you keep accessible at all times?', description: 'The 1-3 month rule, different scenarios', priority: 'high', communities: ['general'] },
      { id: 'lq_3', title: 'Balancing savings, investments, remittances, and emergency fund', description: 'The immigrant budget pyramid', priority: 'high', communities: ['general'] },
      { id: 'lq_4', title: 'Money market accounts vs savings accounts for immigrants', description: 'Rates, FDIC coverage, access rules', priority: 'medium', communities: ['general'] },
      { id: 'lq_5', title: 'Understanding cash flow when income is irregular (gig, tips, seasonal)', description: 'Budgeting with variable income, smoothing cash flow', priority: 'high', communities: ['hispanic_latino', 'african', 'caribbean'] },
      { id: 'lq_6', title: 'Opportunity fund vs emergency fund — what\'s the difference?', description: 'When to hold more cash for opportunities', priority: 'medium', communities: ['general'] },
    ],
  },
  {
    id: 'first_investments',
    name: 'First Investments',
    subtitle: 'Growing Wealth',
    emoji: '📊',
    icon: 'trending-up',
    color: '#558B2F',
    timeline: 'After emergency fund is 3 months of expenses',
    description: 'Making your money work while navigating investment rules for non-citizens.',
    topics: [
      { id: 'fi_1', title: 'Index funds explained for first-generation investors', description: 'S&P 500, ETFs, why they beat most active funds', priority: 'high', communities: ['general'] },
      { id: 'fi_2', title: 'Why immigrants often miss the 401(k) employer match (and how to fix it)', description: 'Free money most immigrants leave on the table', priority: 'high', communities: ['general'] },
      { id: 'fi_3', title: 'Roth IRA vs Traditional IRA — which is better for immigrants?', description: 'Tax-now vs tax-later, income limits, visa considerations', priority: 'high', communities: ['general'] },
      { id: 'fi_4', title: 'Can you invest in the US stock market on a visa?', description: 'F1, H1B, OPT — brokerage rules, tax implications', priority: 'high', communities: ['south_asian', 'east_asian', 'middle_eastern'], visaTypes: ['F1', 'H1B'] },
      { id: 'fi_5', title: 'Dollar-cost averaging explained with a real immigrant example', description: 'Weekly $50 investments over 5 years — real numbers', priority: 'medium', communities: ['general'] },
      { id: 'fi_6', title: 'Investing in your home country vs US — pros and cons', description: 'Currency risk, political risk, diversification', priority: 'medium', communities: ['south_asian', 'african', 'hispanic_latino'] },
      { id: 'fi_7', title: 'What is compound interest — the concept that changes everything', description: 'Simple visual explanation for first-gen investors', priority: 'high', communities: ['general'] },
    ],
  },
  {
    id: 'tax_mastery',
    name: 'Tax Mastery',
    subtitle: 'Filing Correctly & Saving Money',
    emoji: '📋',
    icon: 'file-document-multiple',
    color: '#C62828',
    timeline: 'Every year, January–April',
    description: 'US taxes are complex for immigrants. Get it right and avoid costly mistakes.',
    topics: [
      { id: 'tm_1', title: 'First time filing taxes in the US — step-by-step guide', description: 'Which form to use, free filing options, deadlines', priority: 'high', communities: ['general'] },
      { id: 'tm_2', title: 'ITIN renewal guide 2025 — who needs it and how to do it', description: 'Expiration rules, CAA agents, W-7 form', priority: 'high', communities: ['hispanic_latino', 'south_asian', 'african'], visaTypes: ['Undocumented', 'Tourist'] },
      { id: 'tm_3', title: 'Self-employed immigrant tax guide — what you owe and when', description: 'SE tax, quarterly payments, Schedule C', priority: 'high', communities: ['hispanic_latino', 'african', 'caribbean'] },
      { id: 'tm_4', title: 'Can I claim relatives abroad on my US tax return?', description: 'Qualifying relative rules for non-resident dependents', priority: 'high', communities: ['general'] },
      { id: 'tm_5', title: 'FBAR guide — reporting foreign bank accounts to the IRS', description: 'FinCEN 114, $10k threshold, penalties for non-filing', priority: 'high', communities: ['south_asian', 'east_asian', 'middle_eastern'] },
      { id: 'tm_6', title: '1040-NR vs 1040 — which tax return should you file?', description: 'Resident vs non-resident alien for tax purposes', priority: 'high', communities: ['general'] },
      { id: 'tm_7', title: 'Free tax filing resources for immigrants (VITA, IRS Free File)', description: 'Where to get free help, language support', priority: 'medium', communities: ['general'] },
    ],
  },
  {
    id: 'entrepreneurship',
    name: 'Business & Entrepreneurship',
    subtitle: 'Building Your Own',
    emoji: '🚀',
    icon: 'rocket-launch',
    color: '#F57F17',
    timeline: 'When you are ready to start a business',
    description: 'The immigrant entrepreneur\'s financial roadmap — entity types, banking, funding.',
    topics: [
      { id: 'en_1', title: 'Can immigrants start a business in the US?', description: 'Which visas allow it, H-1B restrictions, LLC vs corp', priority: 'high', communities: ['general'] },
      { id: 'en_2', title: 'LLC vs Sole Proprietorship for immigrant entrepreneurs', description: 'Liability, taxes, banking requirements', priority: 'high', communities: ['general'] },
      { id: 'en_3', title: 'How to get an EIN as a non-citizen (even without SSN)', description: 'IRS form SS-4, phone application, timeline', priority: 'high', communities: ['general'] },
      { id: 'en_4', title: 'Business bank accounts for immigrants — what banks require', description: 'Documentation, credit requirements, ITIN vs EIN', priority: 'high', communities: ['general'] },
      { id: 'en_5', title: 'Small business loans for immigrant entrepreneurs', description: 'SBA microloan, CDFIs, credit union loans', priority: 'high', communities: ['hispanic_latino', 'african', 'caribbean'] },
      { id: 'en_6', title: 'Business taxes for immigrant entrepreneurs', description: 'Quarterly payments, deductions, separate accounts', priority: 'high', communities: ['general'] },
      { id: 'en_7', title: 'Immigrant entrepreneur success stories — financial lessons learned', description: 'Real examples, mistakes and wins', priority: 'medium', communities: ['general'] },
    ],
  },
  {
    id: 'homeownership',
    name: 'Homeownership',
    subtitle: 'Buying Your First Home',
    emoji: '🔑',
    icon: 'home-plus',
    color: '#37474F',
    timeline: 'When credit score is 620+ and emergency fund is solid',
    description: 'Buying a home as an immigrant is possible — even without a Green Card or SSN.',
    topics: [
      { id: 'ho_1', title: 'Can undocumented immigrants buy a home? The ITIN mortgage explained', description: 'Lenders who offer ITIN loans, requirements, rates', priority: 'high', communities: ['hispanic_latino'], visaTypes: ['Undocumented', 'ITIN'] },
      { id: 'ho_2', title: 'Buying a home on H-1B visa — is it smart?', description: 'Visa uncertainty, mortgage approval, resale plan', priority: 'high', communities: ['south_asian', 'east_asian'], visaTypes: ['H1B'] },
      { id: 'ho_3', title: 'First-time homebuyer programs for immigrants', description: 'FHA loans, state programs, down payment assistance', priority: 'high', communities: ['general'] },
      { id: 'ho_4', title: 'Credit score needed to buy a home in 2025', description: 'Conventional vs FHA requirements, how to improve fast', priority: 'high', communities: ['general'] },
      { id: 'ho_5', title: 'The US home buying process — step by step for immigrants', description: 'Pre-approval, offer, inspection, closing explained simply', priority: 'high', communities: ['general'] },
      { id: 'ho_6', title: 'How much home can I afford? The immigrant income calculation', description: 'DTI ratio, 28/36 rule, what banks look at', priority: 'high', communities: ['general'] },
    ],
  },
  {
    id: 'retirement_legacy',
    name: 'Retirement & Legacy',
    subtitle: 'Long-Term Wealth',
    emoji: '🌅',
    icon: 'weather-sunset',
    color: '#4A148C',
    timeline: 'Start thinking about this by year 3 in the US',
    description: 'Building long-term wealth across borders — Social Security, retirement accounts, estate planning.',
    topics: [
      { id: 'rl_1', title: 'Social Security benefits for immigrants — when and how much?', description: '40 quarters rule, totalization agreements, survivor benefits', priority: 'high', communities: ['general'] },
      { id: 'rl_2', title: 'What happens to your 401(k) if you leave the US?', description: 'Rollover options, early withdrawal, leaving it behind', priority: 'high', communities: ['general'] },
      { id: 'rl_3', title: 'How to set up a will as an immigrant', description: 'Cross-border estate planning, choosing beneficiaries abroad', priority: 'high', communities: ['general'] },
      { id: 'rl_4', title: 'Life insurance for immigrants — who needs it and what type', description: 'Term vs whole, visa requirements, international coverage', priority: 'high', communities: ['general'] },
      { id: 'rl_5', title: '529 college savings plans for immigrant families', description: 'Who can contribute, state plans, non-citizen beneficiaries', priority: 'medium', communities: ['general'] },
      { id: 'rl_6', title: 'Teaching kids about money — the immigrant parent edition', description: 'Money values across cultures, age-appropriate financial education', priority: 'medium', communities: ['general'] },
    ],
  },
  {
    id: 'financial_citizenship',
    name: 'Financial Citizenship',
    subtitle: 'The Final Chapter',
    emoji: '🇺🇸',
    icon: 'star-circle',
    color: '#B71C1C',
    timeline: 'Green Card+ / Naturalization path',
    description: 'The financial milestones that come with citizenship and permanent residency.',
    topics: [
      { id: 'fc_1', title: 'Financial changes when you become a US citizen', description: 'Benefits unlocked, global taxation, passport power', priority: 'high', communities: ['general'] },
      { id: 'fc_2', title: 'Renouncing US citizenship — tax consequences (FATCA, exit tax)', description: 'Covered expatriate rules, who it affects', priority: 'medium', communities: ['south_asian', 'east_asian'] },
      { id: 'fc_3', title: 'Dual citizenship and taxes — what you must know', description: 'Countries that allow it, US tax obligations', priority: 'high', communities: ['general'] },
      { id: 'fc_4', title: 'Building generational wealth as an immigrant family', description: 'First generation to second generation wealth transfer', priority: 'high', communities: ['general'] },
      { id: 'fc_5', title: 'The immigrant wealth journey — from $0 to financial independence', description: 'Real timeline, milestones, what to expect', priority: 'high', communities: ['general'] },
    ],
  },
];

export function getStageById(id: string): LifeStage | undefined {
  return LIFE_STAGES.find(s => s.id === id);
}

export function getTopicById(stageId: string, topicId: string) {
  return getStageById(stageId)?.topics.find(t => t.id === topicId);
}

export function getTotalTopics(): number {
  return LIFE_STAGES.reduce((sum, s) => sum + s.topics.length, 0);
}
